name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: docker/build-push-action@v5
      with:
        file: Dockerfile.dev
        context: .
        push: false
        tags: |
          stefanmich/spotifyrandomalbum:${{github.run_number}}
